/*
 * Copyright (c) 2012 Bartlomiej Siwek All rights reserved.
 */

#include "Elg.DirectX/Keyboard.h"

namespace Elg {
namespace DirectX {

VirtualKeyCode g_windows_to_virtual_key_code_[256] = {
  /* 0x00, NONE */ KEY_NONE,
  /* 0x01, LEFT_MOUSE_BUTTON */ KEY_NONE,
  /* 0x02, RIGHT_MOUSE_BUTTON */ KEY_NONE,
  /* 0x03, CANCEL */ KEY_NONE,
  /* 0x04, MIDDLE_MOUSE_BUTTON */ KEY_NONE,
  /* 0x05, XBUTTON1 */ KEY_NONE,
  /* 0x06, XBUTTON2 */ KEY_NONE,
  /* 0x07, Unassigned */ KEY_NONE,
  /* 0x08, BACKSPACE */ KEY_BACKSPACE,
  /* 0x09, TAB */ KEY_TAB,
  /* 0x0A, Reserved */ KEY_NONE,
  /* 0x0B, Reserved */ KEY_NONE,
  /* 0x0C, CLEAR */ KEY_NONE,
  /* 0x0D, RETURN */ KEY_ENTER,
  /* 0x0E, ??? */ KEY_NONE,
  /* 0x0F, ??? */ KEY_NONE,
  /* 0x10, SHIFT */ KEY_LSHIFT,
  /* 0x11, CONTROL */ KEY_LCTRL,
  /* 0x12, MENU */ KEY_ALT,
  /* 0x13, PAUSE */ KEY_PAUSE,
  /* 0x14, CAPS_LOCK */ KEY_CAPSLOCK,
  /* 0x15, KANA / HANGEUL / HANGUL  */ KEY_NONE,
  /* 0x16, ??? */ KEY_NONE,
  /* 0x17, JUNJA */ KEY_NONE,
  /* 0x18, FINAL */ KEY_NONE,
  /* 0x19, HANJA / KANJI */ KEY_NONE,
  /* 0x1A, ??? */ KEY_NONE,
  /* 0x1B, ESCAPE */ KEY_ESCAPE,
  /* 0x1C, CONVERT */ KEY_NONE,
  /* 0x1D, NONCONVERT */ KEY_NONE,
  /* 0x1E, ACCEPT */ KEY_NONE,
  /* 0x1F, MODECHANGE */ KEY_NONE,
  /* 0x20, SPACE */ KEY_SPACE,
  /* 0x21, PAGE_UP */ KEY_PGDN,
  /* 0x22, PAGE_DOWN  */ KEY_PGUP,
  /* 0x23, END */ KEY_END,
  /* 0x24, HOME */ KEY_HOME,
  /* 0x25, ARROW_LEFT */ KEY_LEFT,
  /* 0x26, ARROW_UP */ KEY_UP,
  /* 0x27, ARROW_RIGHT */ KEY_RIGHT,
  /* 0x28, ARROW_DOWN */ KEY_DOWN,
  /* 0x29, SELECT */ KEY_NONE,
  /* 0x2A, PRINT */ KEY_NONE,
  /* 0x2B, EXECUTE */ KEY_NONE,
  /* 0x2C, PRINT_SCREEN */ KEY_PRINTSCREEN,
  /* 0x2D, INSERT */ KEY_INSERT,
  /* 0x2E, DELETE */ KEY_DELETE,
  /* 0x2F, HELP */ KEY_NONE,
  /* 0x30, NUMBER_0 */ KEY_0,
  /* 0x31, NUMBER_1 */ KEY_1,
  /* 0x32, NUMBER_2 */ KEY_2,
  /* 0x33, NUMBER_3 */ KEY_3,
  /* 0x34, NUMBER_4 */ KEY_4,
  /* 0x35, NUMBER_5 */ KEY_5,
  /* 0x36, NUMBER_6 */ KEY_6,
  /* 0x37, NUMBER_7 */ KEY_7,
  /* 0x38, NUMBER_8 */ KEY_8,
  /* 0x39, NUMBER_9 */ KEY_9,
  /* 0x3A, Unassigned */ KEY_NONE,
  /* 0x3B, Unassigned */ KEY_NONE,
  /* 0x3C, Unassigned */ KEY_NONE,
  /* 0x3D, Unassigned */ KEY_NONE,
  /* 0x3E, Unassigned */ KEY_NONE,
  /* 0x3F, Unassigned */ KEY_NONE,
  /* 0x40, Unassigned */ KEY_NONE,
  /* 0x41, A */ KEY_A,
  /* 0x42, B */ KEY_B,
  /* 0x43, C */ KEY_C,
  /* 0x44, D */ KEY_D,
  /* 0x45, E */ KEY_E,
  /* 0x46, F */ KEY_F,
  /* 0x47, G */ KEY_G,
  /* 0x48, H */ KEY_H,
  /* 0x49, I */ KEY_I,
  /* 0x4A, J */ KEY_J,
  /* 0x4B, K */ KEY_K,
  /* 0x4C, L */ KEY_L,
  /* 0x4D, M */ KEY_M,
  /* 0x4E, N */ KEY_N,
  /* 0x4F, O */ KEY_O,
  /* 0x50, P */ KEY_P,
  /* 0x51, Q */ KEY_Q,
  /* 0x52, R */ KEY_R,
  /* 0x53, S */ KEY_S,
  /* 0x54, T */ KEY_T,
  /* 0x55, U */ KEY_U,
  /* 0x56, V */ KEY_V,
  /* 0x57, W */ KEY_W,
  /* 0x58, X */ KEY_X,
  /* 0x59, Y */ KEY_Y,
  /* 0x5A, Z */ KEY_Z,
  /* 0x5B, LEFT_WINDOWS */ KEY_LWIN,
  /* 0x5C, RIGHT_WINDOWS */ KEY_RWIN,
  /* 0x5D, APPLICATIONSS */ KEY_NONE,
  /* 0x5E, Reserved */ KEY_NONE,
  /* 0x5F, SLEEP */ KEY_NONE,
  /* 0x60, NUMPAD0 */ KEY_NUMPAD_0,
  /* 0x61, NUMPAD1 */ KEY_NUMPAD_1,
  /* 0x62, NUMPAD2 */ KEY_NUMPAD_2,
  /* 0x63, NUMPAD3 */ KEY_NUMPAD_3,
  /* 0x64, NUMPAD4 */ KEY_NUMPAD_4,
  /* 0x65, NUMPAD5 */ KEY_NUMPAD_5,
  /* 0x66, NUMPAD6 */ KEY_NUMPAD_6,
  /* 0x67, NUMPAD7 */ KEY_NUMPAD_7,
  /* 0x68, NUMPAD8 */ KEY_NUMPAD_8,
  /* 0x69, NUMPAD9 */ KEY_NUMPAD_9,
  /* 0x6A, MULTIPLY */ KEY_NUMPAD_ASTERISK,
  /* 0x6B, ADD */ KEY_NUMPAD_ENTER,
  /* 0x6C, SEPARATOR */ KEY_NUMPAD_SLASH,
  /* 0x6D, SUBTRACT */ KEY_NUMPAD_MINUS,
  /* 0x6E, DECIMAL */ KEY_NUMPAD_DECIMAL,
  /* 0x6F, DIVIDE */ KEY_NUMPAD_SLASH,
  /* 0x70, F1 */ KEY_F1,
  /* 0x71, F2 */ KEY_F2,
  /* 0x72, F3 */ KEY_F3,
  /* 0x73, F4 */ KEY_F4,
  /* 0x74, F5 */ KEY_F5,
  /* 0x75, F6 */ KEY_F6,
  /* 0x76, F7 */ KEY_F7,
  /* 0x77, F8 */ KEY_F8,
  /* 0x78, F9 */ KEY_F9,
  /* 0x79, F10 */ KEY_F10,
  /* 0x7A, F11 */ KEY_F11,
  /* 0x7B, F12 */ KEY_F12,
  /* 0x7C, F13 */ KEY_NONE,
  /* 0x7D, F14 */ KEY_NONE,
  /* 0x7E, F15 */ KEY_NONE,
  /* 0x7F, F16 */ KEY_NONE,
  /* 0x80, F17 */ KEY_NONE,
  /* 0x81, F18 */ KEY_NONE,
  /* 0x82, F19 */ KEY_NONE,
  /* 0x83, F20 */ KEY_NONE,
  /* 0x84, F21 */ KEY_NONE,
  /* 0x85, F22 */ KEY_NONE,
  /* 0x86, F23 */ KEY_NONE,
  /* 0x87, F24 */ KEY_NONE,
  /* 0x88, Unassigned */ KEY_NONE,
  /* 0x89, Unassigned */ KEY_NONE,
  /* 0x8A, Unassigned */ KEY_NONE,
  /* 0x8B, Unassigned */ KEY_NONE,
  /* 0x8C, Unassigned */ KEY_NONE,
  /* 0x8D, Unassigned */ KEY_NONE,
  /* 0x8E, Unassigned */ KEY_NONE,
  /* 0x8F, Unassigned */ KEY_NONE,
  /* 0x90, NUMLOCK */ KEY_NUMLOCK,
  /* 0x91, SCROLL */ KEY_SCROLLLOCK,
  /* 0x92, OEM_NEC_EQUAL / OEM_FJ_JISHO */ KEY_NONE,
  /* 0x93, OEM_FJ_MASSHOU */ KEY_NONE,
  /* 0x94, OEM_FJ_TOUROKU */ KEY_NONE,
  /* 0x95, OEM_FJ_LOYA */ KEY_NONE,
  /* 0x96, OEM_FJ_ROYA */ KEY_NONE,
  /* 0x97, Unassigned */ KEY_NONE,
  /* 0x98, Unassigned */ KEY_NONE,
  /* 0x99, Unassigned */ KEY_NONE,
  /* 0x9A, Unassigned */ KEY_NONE,
  /* 0x9B, Unassigned */ KEY_NONE,
  /* 0x9C, Unassigned */ KEY_NONE,
  /* 0x9D, Unassigned */ KEY_NONE,
  /* 0x9E, Unassigned */ KEY_NONE,
  /* 0x9F, Unassigned */ KEY_NONE,
  /* 0xA0, LSHIFT */ KEY_LSHIFT,
  /* 0xA1, RSHIFT */ KEY_RSHIFT,
  /* 0xA2, LCONTROL */ KEY_LCTRL,
  /* 0xA3, RCONTROL */ KEY_RCTRL,
  /* 0xA4, LMENU */ KEY_ALT,
  /* 0xA5, RMENU */ KEY_ALT,
  /* 0xA6, BROWSER_BACK */ KEY_NONE,
  /* 0xA7, BROWSER_FORWARD */ KEY_NONE,
  /* 0xA8, BROWSER_REFRESH */ KEY_NONE,
  /* 0xA9, BROWSER_STOP */ KEY_NONE,
  /* 0xAA, BROWSER_SEARCH */ KEY_NONE,
  /* 0xAB, BROWSER_FAVORITES */ KEY_NONE,
  /* 0xAC, BROWSER_HOME */ KEY_NONE,
  /* 0xAD, VOLUME_MUTE */ KEY_NONE,
  /* 0xAE, VOLUME_DOWN */ KEY_NONE,
  /* 0xAF, VOLUME_UP */ KEY_NONE,
  /* 0xB0, MEDIA_NEXT_TRACK */ KEY_NONE,
  /* 0xB1, MEDIA_PREV_TRACK */ KEY_NONE,
  /* 0xB2, MEDIA_STOP */ KEY_NONE,
  /* 0xB3, MEDIA_PLAY_PAUSE */ KEY_NONE,
  /* 0xB4, LAUNCH_MAIL */ KEY_NONE,
  /* 0xB5, LAUNCH_MEDIA_SELECT */ KEY_NONE,
  /* 0xB6, LAUNCH_APP1 */ KEY_NONE,
  /* 0xB7, LAUNCH_APP2 */ KEY_NONE,
  /* 0xB8, Reserved */ KEY_NONE,
  /* 0xB9, Reserved */ KEY_NONE,
  /* 0xBA, OEM_1, ';:' for US */ KEY_SEMICOLON,
  /* 0xBB, OEM_PLUS, '+' any country */ KEY_EQUALS,
  /* 0xBC, OEM_COMMA, ',' any country */ KEY_COMMA,
  /* 0xBD, OEM_MINUS, '-' any country */ KEY_MINUS,
  /* 0xBE, OEM_PERIOD, '.' any country */ KEY_DOT,
  /* 0xBF, OEM_2, '/?' for US */ KEY_SLASH,
  /* 0xC0, OEM_3, '`~' for US */ KEY_TILDE,
  /* 0xC1, Reserved */ KEY_NONE,
  /* 0xC2, Reserved */ KEY_NONE,
  /* 0xC3, Reserved */ KEY_NONE,
  /* 0xC4, Reserved */ KEY_NONE,
  /* 0xC5, Reserved */ KEY_NONE,
  /* 0xC6, Reserved */ KEY_NONE,
  /* 0xC7, Reserved */ KEY_NONE,
  /* 0xC8, Reserved */ KEY_NONE,
  /* 0xC9, Reserved */ KEY_NONE,
  /* 0xCA, Reserved */ KEY_NONE,
  /* 0xCB, Reserved */ KEY_NONE,
  /* 0xCC, Reserved */ KEY_NONE,
  /* 0xCD, Reserved */ KEY_NONE,
  /* 0xCE, Reserved */ KEY_NONE,
  /* 0xCF, Reserved */ KEY_NONE,
  /* 0xD0, Reserved */ KEY_NONE,
  /* 0xD1, Reserved */ KEY_NONE,
  /* 0xD2, Reserved */ KEY_NONE,
  /* 0xD3, Reserved */ KEY_NONE,
  /* 0xD4, Reserved */ KEY_NONE,
  /* 0xD5, Reserved */ KEY_NONE,
  /* 0xD6, Reserved */ KEY_NONE,
  /* 0xD7, Reserved */ KEY_NONE,
  /* 0xD8, Unassigned */ KEY_NONE,
  /* 0xD9, Unassigned */ KEY_NONE,
  /* 0xDA, Unassigned */ KEY_NONE,
  /* 0xDB, OEM_4, '[{' for US */ KEY_OPENBRACE,
  /* 0xDC, OEM_5, '\|' for US */ KEY_BACKSLASH,
  /* 0xDD, OEM_6, ']}' for US */ KEY_CLOSEBRACE,
  /* 0xDE, OEM_7, ''"' for US */ KEY_QUOTE,
  /* 0xDF, OEM_8 */ KEY_NONE,
  /* 0xE0, Reserved */ KEY_NONE,
  /* 0xE1, OEM_AX, 'AX' key on Japanese AX kbd */ KEY_NONE,
  /* 0xE2, OEM_102, "<>" or "\|" on RT 102-key kbd. */ KEY_NONE,
  /* 0xE3, ICO_HELP, Help key on ICO */ KEY_NONE,
  /* 0xE4, ICO_00, 00 key on ICO */ KEY_NONE,
  /* 0xE5, PROCESSKEY */ KEY_NONE,
  /* 0xE6, ICO_CLEAR */ KEY_NONE,
  /* 0xE7, PACKET */ KEY_NONE,
  /* 0xE8, Unassigned */ KEY_NONE,
  /* 0xE9, OEM_RESET */ KEY_NONE,
  /* 0xEA, OEM_JUMP */ KEY_NONE,
  /* 0xEB, OEM_PA1 */ KEY_NONE,
  /* 0xEC, OEM_PA2 */ KEY_NONE,
  /* 0xED, OEM_PA3 */ KEY_NONE,
  /* 0xEE, OEM_WSCTRL */ KEY_NONE,
  /* 0xEF, OEM_CUSEL */ KEY_NONE,
  /* 0xF0, OEM_ATTN */ KEY_NONE,
  /* 0xF1, OEM_FINISH */ KEY_NONE,
  /* 0xF2, OEM_COPY */ KEY_NONE,
  /* 0xF3, OEM_AUTO */ KEY_NONE,
  /* 0xF4, OEM_ENLW */ KEY_NONE,
  /* 0xF5, OEM_BACKTAB */ KEY_NONE,
  /* 0xF6, ATTN */ KEY_NONE,
  /* 0xF7, CRSEL */ KEY_NONE,
  /* 0xF8, EXSEL */ KEY_NONE,
  /* 0xF9, EREOF */ KEY_NONE,
  /* 0xFA, PLAY */ KEY_NONE,
  /* 0xFB, ZOOM */ KEY_NONE,
  /* 0xFC, NONAME */ KEY_NONE,
  /* 0xFD, PA1 */ KEY_NONE,
  /* 0xFE, OEM_CLEAR */ KEY_NONE,
  /* 0xFF, Reserved */ KEY_NONE,
};

VirtualKeyState g_keyboard_state_[KEY_COUNT] = { KEY_STATE_UP };
VirtualKeyState g_keyboard_previous_state_[KEY_COUNT] = { KEY_STATE_UP };

void RegisterKeyDown(VirtualKeyCode key_code) {
  g_keyboard_previous_state_[key_code] = g_keyboard_state_[key_code];
  g_keyboard_state_[key_code] = KEY_STATE_DOWN;
}

void RegisterKeyUp(VirtualKeyCode key_code) {
  g_keyboard_previous_state_[key_code] = g_keyboard_state_[key_code];
  g_keyboard_state_[key_code] = KEY_STATE_UP;
}

VirtualKeyState GetState(VirtualKeyCode key_code) {
  return g_keyboard_state_[key_code];
}

VirtualKeyState GetPreviousState(VirtualKeyCode key_code) {
  return g_keyboard_previous_state_[key_code];
}

VirtualKeyCode GetKeyCode(USHORT windows_key_code) {
  return g_windows_to_virtual_key_code_[windows_key_code];
}

VirtualKeyModifierFlags GetModifierFlags() {
  elg_uint32 modifier_flags = KEY_MODIFIER_NONE;
  modifier_flags |= (g_keyboard_state_[KEY_LSHIFT] * KEY_MODIFIER_SHIFT);
  modifier_flags |= (g_keyboard_state_[KEY_RSHIFT] * KEY_MODIFIER_SHIFT);
  modifier_flags |= (g_keyboard_state_[KEY_LCTRL] * KEY_MODIFIER_CTRL);
  modifier_flags |= (g_keyboard_state_[KEY_RCTRL] * KEY_MODIFIER_CTRL);
  modifier_flags |= (g_keyboard_state_[KEY_ALT] * KEY_MODIFIER_ALT);
  modifier_flags |= (g_keyboard_state_[KEY_LWIN] * KEY_MODIFIER_LWIN);
  modifier_flags |= (g_keyboard_state_[KEY_RWIN] * KEY_MODIFIER_RWIN);

  return static_cast<VirtualKeyModifierFlags>(modifier_flags);
}

}  // namespace DirectX
}  // namespace Elg
